<meta charset="utf-8" />
    <meta name="description" content="Blockchain" />
	<meta name="keywords"    content="blockchain, brief, introduction, quiz" />
	<meta name="author"      content="Rhyanna Arisya" />
	<link href="images/blockchain.png" rel="icon" type="image/gif" sizes="16x16" />
	<link href="styles/style.css" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;600;700&display=swap" rel="stylesheet" /> 
	<link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet" />